name = "tigerbeetle-wasm-worker"
main = "src/index.mjs"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "LEDGER"
class_name = "TigerBeetleLedger"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TigerBeetleLedger"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true
